package:
  name: dagmc_volume_finder
  version: 0.0.3

source:
  - git_url: https://github.com/shimwell/pybind11_python_example.git
    git_rev: 0.0.6
  - url: https://github.com/svalinn/DAGMC/archive/refs/tags/v3.2.1.tar.gz
    sha256: 4d006b2f59f237d6ccb593b2b88b84977532ab2178db4b1b72f12b26416740c6
    folder: vendor/dagmc

build:
  number: 0
  # script: python setup.py install --single-version-externally-managed --record=record.txt
  script: python -m pip install . -vvv

requirements:
  build:
    # - dagmc 3.2.1 * nompi_*  # [dagmc == 'dagmc']
    - {{ compiler('cxx') }}

  host:
    # - dagmc 3.2.1 * nompi_*  # [dagmc == 'dagmc']
    - python
    - pip
    - pybind11 >=2.6.0

  run:
    - python


test:
  imports:
    - dagmc_volume_finder
  source_files:
    - tests
  commands:
    - python tests/test.py

about:
  summary: An example project built with pybind11.
  license_file: LICENSE
