name: Conda

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: ["3.6", "3.8"]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v2

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Prepare
        run: conda install conda-build conda-verify

      - name: install mamba
        run: conda install -c conda-forge mamba

      - name: Build
        run: mamba build -c conda-forge --croot /tmp/conda-build/dagmc-volumer-finder conda

      - name: Install
        run: mamba install -c ${CONDA_PREFIX}/conda-bld/ dagmc_volume_finder

      - name: Test
        run: python tests/test.py
